/* =====================================================================
   Diccionario único de notación del curso (fuente: slides/*.Rmd).
   Lo usan: los símbolos <span class="sym" data-s="clave">, y la tabla
   completa del artefacto 00 (<div data-tabla-notacion>).
   Solo el orquestador edita este archivo. Si un artefacto necesita un
   símbolo nuevo, lo reporta en lugar de agregarlo.

   Campos:  s = cómo se escribe (HTML)   n = nombre
            rol = param | dato | hiper | calc | op   (define el color)
            g = grupo de la tabla   l = cómo se lee en voz alta
            d = qué significa en el curso   ej = ejemplo (opcional)
   ===================================================================== */
window.NOTACION = {

  /* ---------------- datos ---------------- */
  x:      {s:"x", n:"x (entrada)", rol:"dato", g:"datos", l:"«equis», o «el input»",
           d:"La entrada del modelo. Puede ser un número, un vector de características o una imagen entera.",
           ej:"la edad de una persona; los 784 píxeles de un dígito de MNIST"},
  xi:     {s:"x<sub>i</sub>", n:"x sub i", rol:"dato", g:"datos", l:"«equis sub i», o «la entrada de la observación i»",
           d:"La entrada de la i-ésima observación del conjunto de entrenamiento. El subíndice dice de qué fila de los datos hablamos."},
  y:      {s:"y", n:"y (salida verdadera)", rol:"dato", g:"datos", l:"«ye», o «el valor real»",
           d:"La salida observada (la etiqueta o label) que queremos que el modelo prediga.",
           ej:"la estatura real; la clase correcta «7»"},
  X:      {s:"X", n:"matriz de datos", rol:"dato", g:"datos", l:"«equis mayúscula»",
           d:"Todas las entradas juntas en una tabla: una fila por observación y una columna por característica."},
  n:      {s:"n", n:"número de observaciones", rol:"dato", g:"datos", l:"«ene»",
           d:"Cuántos ejemplos hay en el conjunto de entrenamiento. Algunas slides (NN, Regularización) usan I en lugar de n."},
  Imay:   {s:"I", n:"número de observaciones (otra notación)", rol:"dato", g:"datos", l:"«i mayúscula»",
           d:"Lo mismo que n: el número de ejemplos de entrenamiento. Es la notación del libro de Prince."},
  Dtrain: {s:"𝒟<sub>train</sub>", n:"conjunto de entrenamiento", rol:"dato", g:"datos", l:"«de de entrenamiento»",
           d:"La colección de pares (xᵢ, yᵢ), con i de 1 a n, que usamos para ajustar los parámetros."},
  Dval:   {s:"𝒟<sub>val</sub>", n:"conjunto de validación", rol:"dato", g:"datos", l:"«de de validación»",
           d:"Los datos con los que se eligen los hiperparámetros y el modelo. No se usan para ajustar los parámetros."},
  Dtest:  {s:"𝒟<sub>test</sub>", n:"conjunto de test", rol:"dato", g:"datos", l:"«de de test»",
           d:"Los datos reservados para la evaluación final. Se usan una sola vez, al final, y no participan en ninguna decisión."},
  Bt:     {s:"B<sub>t</sub>", n:"mini-batch del paso t", rol:"dato", g:"datos", l:"«be sub te»",
           d:"El subconjunto de observaciones que se usa para calcular el gradiente en el paso t."},
  Di:     {s:"D<sub>i</sub>", n:"dimensión de la entrada", rol:"dato", g:"datos", l:"«de sub i»",
           d:"Cuántos números tiene cada entrada x. Lo fija el problema, no lo elegimos."},
  Do:     {s:"D<sub>o</sub>", n:"dimensión de la salida", rol:"dato", g:"datos", l:"«de sub o»",
           d:"Cuántos números produce la red como salida."},
  Kclases:{s:"K", n:"número de clases", rol:"dato", g:"datos", l:"«ka»",
           d:"En clasificación multiclase, cuántas categorías posibles hay. Ojo: en NN.Rmd, K también es el número de capas."},
  epsruido:{s:"ε<sub>i</sub>", n:"ruido de la observación i", rol:"dato", g:"datos", l:"«épsilon sub i»",
           d:"La parte aleatoria e impredecible de cada dato: y = (parte que el modelo explica) + εᵢ."},

  /* ---------------- parámetros aprendibles ---------------- */
  phi:    {s:"φ", n:"phi (parámetros)", rol:"param", g:"parametros", l:"«fi»",
           d:"El conjunto de TODOS los parámetros que el entrenamiento ajusta. En la red superficial de NN.Rmd, φ₀…φ₃ son además los pesos de la capa de salida.",
           ej:"en la recta y = φ₀ + φ₁x, φ = {φ₀, φ₁}"},
  theta:  {s:"θ", n:"theta (pesos de la capa oculta)", rol:"param", g:"parametros", l:"«teta»",
           d:"Pesos de la capa oculta en la red superficial. θ<sub>d0</sub> es la ordenada al origen de la neurona d y θ<sub>d1</sub> es el peso que multiplica a x.",
           ej:"θ₂₁ = neurona 2, peso de x"},
  psi:    {s:"ψ", n:"psi", rol:"param", g:"parametros", l:"«psi»",
           d:"Nombre nuevo para los parámetros de la segunda capa cuando se juntan dos redes en una sola ecuación."},
  w:      {s:"w", n:"pesos", rol:"param", g:"parametros", l:"«doble u», o «los pesos»",
           d:"Vector de pesos de un modelo lineal: un peso por característica de x."},
  b:      {s:"b", n:"sesgo (bias)", rol:"param", g:"parametros", l:"«be», o «el sesgo»",
           d:"El intercepto: un número que se suma al final y sube o baja toda la función."},
  Omega:  {s:"Ω", n:"Omega (matriz de pesos)", rol:"param", g:"parametros", l:"«omega mayúscula»",
           d:"Matriz de pesos de una capa. Ω<sub>k</sub> lleva la capa k a la siguiente. Tiene una fila por neurona de salida y una columna por entrada."},
  omega:  {s:"ω", n:"omega (peso escalar)", rol:"param", g:"parametros", l:"«omega minúscula»",
           d:"Un peso que es un solo número, como en el ejemplo de backprop con sin, exp y cos encadenados."},
  beta:   {s:"β", n:"beta (sesgos)", rol:"param", g:"parametros", l:"«beta»",
           d:"Vector de sesgos de una capa: β<sub>k</sub> se suma después de multiplicar por Ω<sub>k</sub>. Ojo: en momentum y Adam, β significa otra cosa (ver β₁ y β₂). En BatchNorm, β es el desplazamiento aprendido."},
  gammaBN:{s:"γ", n:"gamma (escala de BatchNorm)", rol:"param", g:"parametros", l:"«gama»",
           d:"Escala aprendible de BatchNorm: después de normalizar se calcula y = γ·x̂ + β."},

  /* ---------------- hiperparámetros ---------------- */
  eta:    {s:"η", n:"eta (tasa de aprendizaje)", rol:"hiper", g:"hiper", l:"«eta»",
           d:"Tamaño del paso en cada actualización. Las slides de Repaso usan η, y las de Entrenamiento y Regularización usan α para lo mismo."},
  alpha:  {s:"α", n:"alfa (tasa de aprendizaje)", rol:"hiper", g:"hiper", l:"«alfa»",
           d:"La tasa de aprendizaje, igual que η. Si es muy chica, el entrenamiento es lentísimo; si es muy grande, diverge."},
  lambda: {s:"λ", n:"lambda (fuerza de regularización)", rol:"hiper", g:"hiper", l:"«lambda»",
           d:"Cuánto pesa la penalización frente a la pérdida. Con λ = 0 no hay regularización; con λ grande, los pesos se encogen mucho. Ojo: en Entrenamiento, λ es una probabilidad (ver λ de Bernoulli)."},
  D:      {s:"D", n:"neuronas por capa", rol:"hiper", g:"hiper", l:"«de»",
           d:"Número de unidades ocultas (neuronas) de una capa: el ancho de la red."},
  Dk:     {s:"D<sub>k</sub>", n:"neuronas de la capa k", rol:"hiper", g:"hiper", l:"«de sub ka»",
           d:"El ancho de la capa k cuando cada capa puede tener distinto número de neuronas."},
  Kcapas: {s:"K", n:"número de capas ocultas", rol:"hiper", g:"hiper", l:"«ka»",
           d:"La profundidad de la red. Ojo: en clasificación, K es el número de clases."},
  Dh:     {s:"D<sub>h</sub>", n:"fan-in (entradas de la capa)", rol:"hiper", g:"hiper", l:"«de sub hache»",
           d:"Cuántas entradas recibe cada neurona de la capa: el número de neuronas de la capa anterior. Es el D<sub>h</sub> de la inicialización He, σ²<sub>Ω</sub> = 2/D<sub>h</sub>."},
  Din:    {s:"D<sub>in</sub>, D<sub>out</sub>", n:"fan-in y fan-out", rol:"hiper", g:"hiper", l:"«de in, de out»",
           d:"Entradas (fan-in) y salidas (fan-out) de una capa. Xavier usa los dos: σ²<sub>Ω</sub> = 2/(D<sub>in</sub> + D<sub>out</sub>)."},
  batch:  {s:"|B|", n:"tamaño del mini-batch", rol:"hiper", g:"hiper", l:"«tamaño de be»",
           d:"Cuántas observaciones entran en cada mini-batch (batch size). Las barras |·| significan «cuántos elementos tiene»."},
  betam:  {s:"β", n:"beta de momentum", rol:"hiper", g:"hiper", l:"«beta»",
           d:"En momentum, cuánto peso se le da a la dirección acumulada frente al gradiente nuevo. Un valor típico es 0.9."},
  beta1:  {s:"β<sub>1</sub>", n:"beta uno (Adam)", rol:"hiper", g:"hiper", l:"«beta uno»",
           d:"Qué tanta memoria tiene el promedio de gradientes en Adam. Un valor típico es 0.9."},
  beta2:  {s:"β<sub>2</sub>", n:"beta dos (Adam)", rol:"hiper", g:"hiper", l:"«beta dos»",
           d:"Qué tanta memoria tiene el promedio de gradientes al cuadrado en Adam. Un valor típico es 0.999."},
  eps:    {s:"ε", n:"épsilon (estabilizador)", rol:"hiper", g:"hiper", l:"«épsilon»",
           d:"Un número muy pequeño (por ejemplo 10⁻⁸) que se suma para nunca dividir entre cero, como en Adam o BatchNorm."},
  pdrop:  {s:"p", n:"probabilidad de dropout", rol:"hiper", g:"hiper", l:"«pe»",
           d:"La probabilidad de apagar (poner en 0) cada neurona durante el entrenamiento."},
  sigmaOm:{s:"σ<sub>Ω</sub><sup>2</sup>", n:"varianza de inicialización", rol:"hiper", g:"hiper", l:"«sigma omega al cuadrado»",
           d:"La varianza de la Normal de la que se sacan los pesos iniciales. He usa 2/D<sub>h</sub>; Xavier usa 2/(D<sub>in</sub> + D<sub>out</sub>)."},

  /* ---------------- cantidades calculadas ---------------- */
  yhat:   {s:"ŷ", n:"y gorro (predicción)", rol:"calc", g:"calculadas", l:"«ye gorro»",
           d:"La predicción del modelo. El gorrito ^ siempre significa «estimado»."},
  phihat: {s:"φ̂", n:"phi gorro", rol:"calc", g:"calculadas", l:"«fi gorro»",
           d:"Los parámetros que encontró el entrenamiento: el mejor φ según la pérdida."},
  f:      {s:"f(x, φ)", n:"el modelo", rol:"calc", g:"calculadas", l:"«efe de equis y fi»",
           d:"La función que toma la entrada x y los parámetros φ, y devuelve una predicción. Antes de la coma va el dato; después, los parámetros."},
  fk:     {s:"f<sub>k</sub>", n:"pre-activación de la capa k", rol:"calc", g:"calculadas", l:"«efe sub ka»",
           d:"Lo que sale de β<sub>k</sub> + Ω<sub>k</sub>h<sub>k</sub>, ANTES de aplicar la activación. No es lo mismo que el modelo f(x, φ)."},
  h:      {s:"h", n:"unidad oculta / activación", rol:"calc", g:"calculadas", l:"«hache»",
           d:"Lo que produce una neurona DESPUÉS de aplicar la activación. Con subíndice (h₁, h₂) es una neurona; en negrita o como h<sub>k</sub> es el vector de toda una capa."},
  z:      {s:"z", n:"entrada de la activación", rol:"calc", g:"calculadas", l:"«zeta»",
           d:"Nombre genérico de lo que entra a una función de activación, por ejemplo z = wᵀx + b."},
  ell:    {s:"ℓ", n:"pérdida de una observación", rol:"calc", g:"calculadas", l:"«ele», o «la pérdida del ejemplo i» si lleva subíndice",
           d:"Qué tan mal predice el modelo UN solo ejemplo. Se usa una ele cursiva para distinguirla de la pérdida total L."},
  L:      {s:"L(φ)", n:"pérdida total", rol:"calc", g:"calculadas", l:"«ele de fi»",
           d:"La pérdida sumada o promediada sobre todo el entrenamiento. Es la función que entrenar busca minimizar, y depende de los parámetros φ."},
  Ltilde: {s:"L̃", n:"pérdida modificada", rol:"calc", g:"calculadas", l:"«ele tilde»",
           d:"La pérdida «efectiva» que en realidad minimizan GD o SGD: la original más términos extra. Es la base de la regularización implícita."},
  grad:   {s:"∇<sub>φ</sub>L", n:"gradiente", rol:"calc", g:"calculadas", l:"«gradiente de L respecto a fi»",
           d:"Vector con una derivada parcial por parámetro. Apunta hacia donde la pérdida SUBE más rápido; por eso en cada paso se resta."},
  gt:     {s:"g<sub>t</sub>", n:"gradiente del mini-batch", rol:"calc", g:"calculadas", l:"«ge sub te»",
           d:"El gradiente calculado con el mini-batch del paso t. Es una estimación ruidosa del gradiente total."},
  mt:     {s:"m<sub>t</sub>", n:"momento (promedio de gradientes)", rol:"calc", g:"calculadas", l:"«eme sub te»",
           d:"Promedio móvil de los gradientes recientes: la «inercia» que usan momentum y Adam."},
  vt:     {s:"v<sub>t</sub>", n:"promedio de gradientes al cuadrado", rol:"calc", g:"calculadas", l:"«ve sub te»",
           d:"En Adam, mide qué tan grandes suelen ser los gradientes de cada parámetro, para ajustar su tamaño de paso."},
  mhat:   {s:"m̂<sub>t</sub>, v̂<sub>t</sub>", n:"momentos corregidos", rol:"calc", g:"calculadas", l:"«eme gorro, ve gorro»",
           d:"Las versiones de m y v corregidas por sesgo. Al inicio m y v valen 0 y subestiman; dividir entre (1 − βᵗ) lo arregla."},
  delta:  {s:"δ<sub>k</sub>", n:"delta (error que viaja hacia atrás)", rol:"calc", g:"calculadas", l:"«delta sub ka»",
           d:"∂ℓ/∂f<sub>k</sub>: cuánto cambiaría la pérdida si cambiara la pre-activación de la capa k. Backprop la calcula de la última capa a la primera."},
  lambdap:{s:"λ", n:"lambda (probabilidad o tasa)", rol:"calc", g:"calculadas", l:"«lambda»",
           d:"En clasificación binaria, la probabilidad de que y = 1 que predice el modelo: λ = σ(f(x, φ)). En Poisson, el número promedio de eventos."},
  mu:     {s:"μ", n:"mu (media)", rol:"calc", g:"calculadas", l:"«mu»",
           d:"El centro de una distribución Normal. En regresión, la red predice μ."},
  sigma:  {s:"σ", n:"sigma (desviación estándar)", rol:"calc", g:"calculadas", l:"«sigma»",
           d:"Qué tan dispersa es una distribución. σ² es la varianza. Ojo: σ(z) con paréntesis es la función sigmoide."},
  muB:    {s:"μ<sub>B</sub>, σ<sub>B</sub><sup>2</sup>", n:"estadísticas del batch", rol:"calc", g:"calculadas", l:"«mu be, sigma be al cuadrado»",
           d:"Media y varianza de las activaciones dentro del mini-batch, que usa BatchNorm."},
  xhat:   {s:"x̂", n:"x gorro (normalizada)", rol:"calc", g:"calculadas", l:"«equis gorro»",
           d:"En BatchNorm, la activación ya normalizada: x̂ = (x − μ<sub>B</sub>) / √(σ<sub>B</sub>² + ε)."},
  R:      {s:"R(f)", n:"riesgo de población", rol:"calc", g:"calculadas", l:"«erre de efe»",
           d:"El error promedio que tendría el modelo sobre TODOS los datos posibles. Es lo que nos importa, pero no se puede calcular."},
  Rhat:   {s:"R̂<sub>train</sub>", n:"riesgo empírico", rol:"calc", g:"calculadas", l:"«erre gorro de entrenamiento»",
           d:"El error promedio sobre los datos de entrenamiento. Se puede calcular, pero es optimista."},

  /* ---------------- funciones ---------------- */
  a:      {s:"a(·)", n:"función de activación", rol:"op", g:"funciones", l:"«a de…»",
           d:"La no linealidad que se aplica a cada neurona después de la parte lineal (ReLU, sigmoide, tanh…). Sin ella, la red entera colapsa a una función lineal."},
  aprima: {s:"a′(·)", n:"derivada de la activación", rol:"op", g:"funciones", l:"«a prima»",
           d:"La pendiente de la activación. Para ReLU vale 1 si la entrada es positiva y 0 si no. Para la sigmoide es casi 0 en los extremos (saturación)."},
  relu:   {s:"ReLU(z)", n:"ReLU", rol:"op", g:"funciones", l:"«relu de zeta»",
           d:"max(0, z): deja pasar los números positivos y convierte los negativos en 0."},
  sigmoide:{s:"σ(z)", n:"sigmoide", rol:"op", g:"funciones", l:"«sigmoide de zeta»",
           d:"σ(z) = 1 / (1 + e<sup>−z</sup>). Aplasta cualquier número real al intervalo (0, 1), así que convierte un score en una probabilidad."},
  tanh:   {s:"tanh(z)", n:"tangente hiperbólica", rol:"op", g:"funciones", l:"«tangente hiperbólica de zeta»",
           d:"Como la sigmoide, pero va de −1 a 1 y está centrada en 0."},
  softmax:{s:"softmax<sub>k</sub>(z)", n:"softmax", rol:"op", g:"funciones", l:"«softmax ka de zeta»",
           d:"Convierte K scores en K probabilidades que suman 1: e<sup>z<sub>k</sub></sup> dividido entre la suma de todos los e<sup>z<sub>j</sub></sup>."},
  exp:    {s:"e<sup>z</sup>", n:"exponencial", rol:"op", g:"funciones", l:"«e a la zeta»",
           d:"Siempre da un número positivo; e ≈ 2.718. Se usa para garantizar que algo sea positivo, como una varianza o una tasa de Poisson."},
  log:    {s:"log(z)", n:"logaritmo natural", rol:"op", g:"funciones", l:"«logaritmo de zeta»",
           d:"La inversa de exp. Su propiedad clave convierte productos en sumas: log(a·b) = log a + log b."},
  indic:  {s:"𝟙[·]", n:"función indicadora", rol:"op", g:"funciones", l:"«indicadora de…»",
           d:"Vale 1 si lo de adentro es verdadero y 0 si es falso. Por ejemplo, 𝟙[f > 0] es la derivada de ReLU."},

  /* ---------------- operadores y notación ---------------- */
  sum:    {s:"Σ", n:"sumatoria", rol:"op", g:"operadores", l:"«la suma de…»",
           d:"Suma de muchos términos. Σ<sub>i=1</sub><sup>n</sup> ℓ<sub>i</sub> significa ℓ₁ + ℓ₂ + … + ℓₙ: «la suma de ℓ sub i, con i desde 1 hasta n»."},
  prod:   {s:"Π", n:"productoria", rol:"op", g:"operadores", l:"«el producto de…»",
           d:"Como Σ, pero multiplicando: Π<sub>i</sub> P<sub>i</sub> = P₁ · P₂ · … · Pₙ."},
  argmin: {s:"argmin", n:"argumento mínimo", rol:"op", g:"operadores", l:"«el valor de… que minimiza…»",
           d:"No es el valor mínimo de la función, sino EL PUNTO donde se alcanza. argmin<sub>φ</sub> L(φ) es «el φ que hace más pequeña a L»."},
  argmax: {s:"argmax", n:"argumento máximo", rol:"op", g:"operadores", l:"«el valor de… que maximiza…»",
           d:"El punto donde una función alcanza su máximo. En clasificación, argmax<sub>k</sub> P(y = k | x) es la clase más probable."},
  partial:{s:"∂", n:"derivada parcial", rol:"op", g:"operadores", l:"«derivada parcial de… respecto a…»",
           d:"∂L/∂φ₁ responde: si muevo un poquito φ₁ y dejo fijos los demás parámetros, ¿cuánto y hacia dónde cambia L?"},
  transp: {s:"ᵀ", n:"transpuesta", rol:"op", g:"operadores", l:"«transpuesta»",
           d:"Voltea una matriz: las filas se vuelven columnas. wᵀx es el producto punto w₁x₁ + w₂x₂ + … (un solo número)."},
  hadamard:{s:"⊙", n:"producto elemento a elemento", rol:"op", g:"operadores", l:"«por, elemento a elemento»",
           d:"Multiplica dos vectores del mismo tamaño posición por posición: (1, 2) ⊙ (3, 4) = (3, 8)."},
  norma:  {s:"‖w‖²", n:"norma al cuadrado", rol:"op", g:"operadores", l:"«norma de w al cuadrado»",
           d:"La suma de los cuadrados de los pesos: w₁² + w₂² + … Mide qué tan grandes son los pesos en conjunto."},
  asigna: {s:"←", n:"actualización", rol:"op", g:"operadores", l:"«se reemplaza por»",
           d:"Asignación: w ← w − η·g significa que el nuevo w es el viejo w menos η·g."},
  implica:{s:"⇒", n:"implica", rol:"op", g:"operadores", l:"«implica», o «entonces»",
           d:"Si se cumple lo de la izquierda, se cumple lo de la derecha. Con una diagonal encima (⇏) significa que NO implica."},
  techo:  {s:"⌈·⌉", n:"techo", rol:"op", g:"operadores", l:"«techo de…»",
           d:"El entero más chico que es mayor o igual al número: ⌈15.6⌉ = 16. Sirve para contar mini-batches cuando n no es múltiplo de |B|."},
  aprox:  {s:"≈", n:"aproximadamente igual", rol:"op", g:"operadores", l:"«aproximadamente»",
           d:"Los dos lados son casi iguales, bajo los supuestos del momento."},
  pertenece:{s:"∈", n:"pertenece a", rol:"op", g:"operadores", l:"«pertenece a», o «está en»",
           d:"y ∈ {0, 1} significa que y vale 0 o 1. λ ∈ [0, 1] significa que λ está entre 0 y 1."},
  reales: {s:"ℝ", n:"los números reales", rol:"op", g:"operadores", l:"«los reales»",
           d:"Todos los números, positivos y negativos, con decimales. «f(x, φ) ∈ ℝ» quiere decir que el modelo puede devolver cualquier número."},
  binom:  {s:"C(D, j)", n:"combinaciones", rol:"op", g:"operadores", l:"«de D en j»",
           d:"De cuántas formas se pueden elegir j cosas de un total de D. Aparece al contar regiones lineales (Zaslavsky). En las slides se escribe como un paréntesis alto con D arriba y j abajo."},
  indice_i:{s:"i", n:"índice de observación", rol:"op", g:"operadores", l:"«i»",
           d:"Un contador que recorre los ejemplos: i = 1, 2, …, n. Cuando algo lleva subíndice i, es «de la observación i»."},
  indice_t:{s:"t", n:"índice de paso", rol:"op", g:"operadores", l:"«te»",
           d:"Cuenta las iteraciones del entrenamiento: φ<sub>t</sub> son los parámetros en el paso t y φ<sub>t+1</sub> los del paso siguiente."},
  indice_k:{s:"k", n:"índice de capa o de clase", rol:"op", g:"operadores", l:"«ka»",
           d:"Recorre las capas de la red (k = 0, 1, …) o, en clasificación, las clases. El contexto dice cuál."},
  Mbatches:{s:"M", n:"número de mini-batches", rol:"op", g:"operadores", l:"«eme»",
           d:"En regularización implícita, el número de mini-batches que se consideran al medir cuánto varían sus gradientes."},
  algo:   {s:"𝒜", n:"algoritmo de entrenamiento", rol:"op", g:"operadores", l:"«a caligráfica»",
           d:"El procedimiento completo que convierte datos en un modelo: f̂ = 𝒜(𝒟<sub>train</sub>)."},

  /* ---------------- probabilidad ---------------- */
  P:      {s:"P(y | x)", n:"probabilidad condicional", rol:"op", g:"probabilidad", l:"«probabilidad de ye dado equis»",
           d:"Qué tan probable es y si ya conocemos x. La barra | se lee «dado». A la derecha de la barra va lo que tomamos como conocido."},
  dist:   {s:"~", n:"se distribuye como", rol:"op", g:"probabilidad", l:"«se distribuye como»",
           d:"ε ~ N(0, σ²) significa que ε es aleatorio y sigue una Normal con media 0 y varianza σ²."},
  normal: {s:"N(μ, σ²)", n:"distribución Normal", rol:"op", g:"probabilidad", l:"«normal con media mu y varianza sigma cuadrada»",
           d:"La campana. Sirve para números reales (regresión) y, con máxima verosimilitud, lleva a la pérdida cuadrática (MSE)."},
  bern:   {s:"Bernoulli(λ)", n:"distribución Bernoulli", rol:"op", g:"probabilidad", l:"«bernoulli de lambda»",
           d:"Para resultados sí/no (y ∈ {0, 1}): P(y = 1) = λ. Con máxima verosimilitud lleva a la binary cross-entropy."},
  cat:    {s:"Categórica(λ<sub>1</sub>…λ<sub>K</sub>)", n:"distribución Categórica", rol:"op", g:"probabilidad", l:"«categórica»",
           d:"Para elegir una de K clases, cada una con su probabilidad λ<sub>k</sub> (todas suman 1). Lleva a la cross-entropy multiclase."},
  poisson:{s:"Poisson(λ)", n:"distribución Poisson", rol:"op", g:"probabilidad", l:"«poisson de lambda»",
           d:"Para conteos (0, 1, 2, …): λ es el número promedio de eventos y tiene que ser positivo. Aparece en la Tarea 3."},
  iid:    {s:"i.i.d.", n:"independientes e idénticamente distribuidas", rol:"op", g:"probabilidad", l:"«i i de»",
           d:"Cada observación es independiente de las otras y todas vienen de la misma distribución. Es lo que permite escribir la verosimilitud como un producto."},
  E:      {s:"E[·]", n:"esperanza (valor esperado)", rol:"op", g:"probabilidad", l:"«valor esperado de…»",
           d:"El promedio que obtendrías si repitieras el experimento infinitas veces."},
  Var:    {s:"Var(·)", n:"varianza", rol:"op", g:"probabilidad", l:"«varianza de…»",
           d:"Qué tanto se dispersa algo alrededor de su promedio: E[(X − E[X])²]."},
  KL:     {s:"D<sub>KL</sub>(q‖p)", n:"divergencia KL", rol:"op", g:"probabilidad", l:"«divergencia de Kullback-Leibler de q a p»",
           d:"Qué tan distinta es la distribución p (la del modelo) de la q (la real). Vale 0 solo si son iguales."},
  H:      {s:"H(q, p)", n:"cross-entropy", rol:"op", g:"probabilidad", l:"«entropía cruzada de q y p»",
           d:"−Σ q(y) log p(y). Minimizarla equivale a minimizar la KL, y con etiquetas one-hot es exactamente la negative log-likelihood."},
  prior:  {s:"P(φ)", n:"prior", rol:"op", g:"probabilidad", l:"«la prior de fi»",
           d:"Lo que creemos sobre los parámetros ANTES de ver los datos. Una prior Normal centrada en 0 da la regularización L2."},
  pxy:    {s:"p(x, y)", n:"distribución de la población", rol:"op", g:"probabilidad", l:"«pe de equis, ye»",
           d:"Cómo se generan realmente los datos en el mundo. No la conocemos; solo tenemos una muestra de ella."}
};
